version: '2'

services:
  app:
    image: 'student-record-app:latest'
    build:
      context: .
    container_name: student-app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/studentrecord
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=studentrecord
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root